katalog/urls.py
# TODO: Implement Routings Here

from django.urls import path
from katalog.views import show_catalog

app_name = 'katalog'

urlpatterns = [
    path('', show_catalog, name='show_catalog'),
]

project_django/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('example_app.urls')),
    path('katalog/',include('katalog.urls')),
    path('mywatchlist/',include('mywatchlist.urls')),
    path('todolist/', include('todolist.urls')),
    # path("__reload__/", include("django_browser_reload.urls")),
]

# TODO: Implement Routings Here

todolist/urls.py
from django.urls import path
from todolist.views import show_todolist, create_task, register, login_user, logout_user, refresh, delete, show_json, create_task_ajax

app_name = 'todolist'

urlpatterns = [
    path('', show_todolist, name='show_todolist'),
    path('create-task/', create_task, name='create_task'),
    path('register/', register, name='register'),
    path('login-user/', login_user, name='login_user'),
    path('logout-user/', logout_user, name='logout_user'),
    path('refresh/<str:id>/', refresh, name="refresh"),
    path('delete/<str:id>/', delete, name="delete"),
    path('json/', show_json, name='show_json'),
    path('create/', create_task_ajax, name='create_task_ajax')
]

todolist/models.py
import datetime
from django.db import models
from django.contrib.auth.models import User
import datetime

# Create your models here.
class Task(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    date = models.DateField(default=datetime.date.today)
    title = models.CharField(max_length=250)
    description = models.TextField()
    is_finished = models.BooleanField(default=False)

todolist/forms.py
from django.forms import DateInput, ModelForm
from todolist.models import Task
from django import forms

class TaskForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = ['title', 'description']

todolist/views.py
import datetime
from django.urls import reverse
from django.core import serializers
from todolist.forms import TaskForm
from django.contrib import messages
from todolist.models import Task
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout
from django.views.decorators.csrf import csrf_exempt

# Create your views here.

#-----------------------------Authentication/Authorization--------------------------------------#
def register(request):
    form = UserCreationForm()

    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Account successfully created!')
            return redirect('todolist:login_user')

    context = {'form':form}
    return render(request, 'register.html', context)

def login_user(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('todolist:show_todolist')
        else:
            messages.info(request, 'Wrong Username or Password!')
    context = {}
    return render(request, 'login_user.html', context)

def logout_user(request):
    logout(request)
    return redirect('todolist:login_user')
#---------------------------------------------------------------------------------------------#

#--------------------------------------------VIEWS--------------------------------------------#
@login_required(login_url='/todolist/login-user/')
def show_todolist(request):
    if request.user.is_authenticated:
        user_name = request.user.username 
        data_tasklist = Task.objects.filter(user= request.user)
        context = {'todolist': data_tasklist, 
                    'username': user_name,
        }
    return render(request, 'todolist.html', context)

@login_required(login_url='/todolist/login-user/') # login first before doing this
def create_task(request):
    user_name = User.objects.get(username=request.user)    
    form = TaskForm()
    new_task = None
    if request.method == 'POST':
        form = TaskForm(request.POST)
        if form.is_valid():
            new_task = form.save(commit=False)
            new_task.user = request.user
            new_task.save()
        return HttpResponseRedirect(reverse("todolist:show_todolist"))
    context = {'form': form}
    return render(request, 'create_task.html', context)

#---------------------------------AJAX Implementation-----------------------------------------#
def create_task_ajax(request):
     if request.method == 'POST':
        title = request.POST.get('title')
        description = request.POST.get('description')
        user = request.user
        date = datetime.datetime.now()
        is_finished = False
        item = Task(title=title, description=description, user=user, date=date, is_finished=is_finished)
        item.save()
        return JsonResponse({"Message": "Task Success"},status=200)

def show_json(request):
    task = Task.objects.filter(user=request.user)
    return HttpResponse(serializers.serialize("json", task), content_type="application/json")

@csrf_exempt
def refresh(request, id):
    task = Task.objects.get(user=request.user, id=id)
    task.is_finished = not(task.is_finished)
    task.save(update_fields = ['is_finished'])
    return JsonResponse({"Message": "Task Updated"},status=200)

@csrf_exempt
def delete(request, id):
    task = Task.objects.get(user=request.user, id=id)
    task.delete()
    return JsonResponse({"Message": "Task Deleted"},status=200)
#---------------------------------------------------------------------------------------------#

todolist/templates/create_task.html
{% extends 'base.html' %}

{% block meta %}
<title>Create Task</title>
{% endblock meta %}

{% block content %}  
<style>
    body {
        background-color: #272727;
        align-items: center;
        display: flex;
        justify-content: center;
        height: 100vh;
    }
    .Create-Task {
        color:whitesmoke;
    }
</style>
<body>
    <div class = "Create-Task">
    
        <h1>Create Task</h1>  
    
            <form method="POST" >  
                {% csrf_token %}  
                <table>  
                    {{ form }}  
                    <tr>  
                        <td><input type="submit" name="submit" value="Save"/></td>  
                    </tr>  
                </table>  
            </form>
    
        {% if messages %}  
            <ul>   
                {% for message in messages %}  
                    <li>{{ message }}</li>  
                    {% endfor %}  
            </ul>   
        {% endif %}
        <button><a href="{% url 'todolist:show_todolist' %}">Back</a></button>
    </div> 
    
    {% endblock content %}
</body>

todolist/templates/login_user.html
{% extends 'base.html' %}

{% block meta %}
<title>Login</title>
{% endblock meta %}

{% block content %}
<!--CSS DESIGN-->
<style>
body {
        background-color: #272727;
        align-items: center;
        display: flex;
        justify-content: center;
        height: 100vh;
    }
    .login_user {
        border: 5px outset rgb(182, 182, 182);
        color:whitesmoke;
        background-color:#9b9b9b73;
        margin:auto;
        padding: 50px
    }
    .submittion {
        color:darkgray
    }
    .form-control {
        color:darkgray;
        text-align: center;
    }
    a:active, a:hover {
        color:red
    }
    a:visited, a:link {
        color: lightcoral
    }
</style>

<!--HTML -->

<body>
    <div class = "login_user">

        <h1>Login</h1>
    
        <form method="POST" action="">
            {% csrf_token %}
            <table>
                <tr>
                    <td>Username: </td>
                    <td><input type="text" name="username" placeholder="Username" class="form-control"></td>
                </tr>
    
                <tr>
                    <td>Password: </td>
                    <td><input type="password" name="password" placeholder="Password" class="form-control"></td>
                </tr>
    
                <tr>
                    <td></td>
                    <td><input class="submittion" type="submit" value="Login"></td>
                </tr>
            </table>
        </form>
    
        {% if messages %}
            <ul>
                {% for message in messages %}
                    <li>{{ message }}</li>
                {% endfor %}
            </ul>
        {% endif %}
    
        Don't have an account? <a href="{% url 'todolist:register' %}">Create Account</a>
    
    </div>
    
    {% endblock content %}
</body>

todolist/templates/register.html
{% extends 'base.html' %}

{% block meta %}
<title>Account Registration</title>
{% endblock meta %}

{% block content %}

<style>
    body {
        background-color: #272727;;
        align-items: center;
        display: flex;
        justify-content: center;
        height: 100vh;
    }
    .login_user {
        color: whitesmoke;
        border:5px outset rgb(255, 255, 255);
        padding:20px;
        background: radial-gradient(#000000, #3f3f3f);
    }
</style>

<body>
    <div class = "login_user">
        <h1>Registration Form</h1>
    
            <form method="POST" >
                {% csrf_token %}
                <table>
                    {{ form.as_table }}
                    <tr>
                        <td></td>
                        <td><input type="submit" name="submit" value="Register"/></td>
                    </tr>
                </table>
            </form>
    
        {% if messages %}
            <ul>
                {% for message in messages %}
                    <li>{{ message }}</li>
                    {% endfor %}
            </ul>
        {% endif %}
    
    </div>
    
    {% endblock content %}
</body>

todolist/templates/todolist.html
{% extends 'base.html' %}
{% load static %}
<head>
  {% block meta %}
  <title>Your todolist</title>
  {% endblock meta %}
</head>

 {% block content %}
 <body class="body bg-[#0f172a]">
    <div class="todolist-container p-6 m-5 bg-[#1e293b] border-gray-700 border-b rounded">
    
        <div class="header p-1 m-1 text-2xl font-bold text-[#e2e8f0]">
            <h1>{{user}}'s to-do list </h1>
        </div>
    
            <div class="container d-flex flex-wrap flex-row " id= "card-container"> </div>
    
    <!-- Modal -->
    <div class="modal fade bg-[#0f172a]" id="modalForm" role="dialog">
        <div class="modal-dialog">
            <div class="modal-content bg-[#1e293b]">
                <!-- Modal Header -->
                <div class="modal-header
                            ">
                    <button type="button" class="close p-1 m-1 bg-orange-600 rounded" data-bs-dismiss="modal">
                        <span aria-hidden="true">&times;</span>
                        <span class="sr-only">Close</span>
                    </button>
                    <h4 class="modal-title font-bold text-[#e2e8f0]" id="myModalLabel">Add Task</h4>
                </div>
                
                <!-- Modal Body -->
                <div class="modal-body">
                    <p class="statusMsg"></p>
                    <form role="form" id="taskForm" action="/todolist/add/" method="POST">
                        {% csrf_token %}
                        <div class="form-group p-2 m-2">
                            <label for="inputTitle" class="text-[#e2e8f0]">Title</label>
                            <input type="text" class="form-control w-100" id="inputTitle" name='title'/>
                        </div>
                        <div class="form-group p-2 m-2">
                            <label for="inputDescription" class="text-[#e2e8f0]">Description</label>
                            <textarea class="form-control" id="inputDescription" name='description'></textarea>
                        </div>
                    </form>
                </div>
                
                <!-- Modal Footer -->
                <div class="modal-footer">
                    <button type="button" class="btn btn-default h-25 bg-orange-600 group-hover:bg-blue-600" data-bs-dismiss="modal">Close</button>
                    <button type="submit" onclick = "submitForm()" class="btn btn-primary submitBtn h-25 bg-orange-600" id="submit">Submit</button>
                </div>
            </div>
        </div>
    </div>
    <button class= "btn-create p-1 m-2 bg-orange-600 text-black group-hover:text-white rounded"><a href="{% url 'todolist:create_task' %}">Create Task</a></button>
    <button class="btn-logout p-1 m-2 bg-orange-600 text-black group-hover:text-white rounded"><a href="{% url 'todolist:logout_user' %}">Logout</a></button>
    <button onclick="myFunction()" class= "button-add p-1 m-2 bg-green-500 text-black group-hover:text-white rounded">Add Task</button>
    </div>
 </body>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
<script>

    function myFunction(){
        $('#modalForm').modal('show') 
    }

    function showJson(){
        $.get("/todolist/json/", function(data){
            for(i = 0; i < data.length; i++){
                addText(data[i].fields.title, data[i].fields.description, data[i].fields.is_finished, data[i].fields.date, data[i].fields.pk)
            }
        })
    }


    $(document).ready(function(){
        showJson();
        makeCards();
    })

    

    function makeCards(){
        let text= "";
        $.ajax({
            url: "{% url 'todolist:show_json' %}",
            type: "GET",
            dataType: "json",
            success: function(data){
                for(let task of data){
                    text += `<div class="m-2 card p-2">
                        <p class="text font-weight-bold">Task : ${task.fields.title}</p>
                        <p>Description : ${task.fields.description}</p>
                        <p>Created : ${task.fields.date}</p>
                        <p>Status : 
                            <span class=" ${task.fields.is_finished ? 'text-success Unfinished':'text-danger Completed'}">
                                ${task.fields.is_finished ? 'Nice':'Do it NOW!'}
                            </span>
                        </p>
                        <button class="btn" onclick="delete_todolist(${task.pk})"><a><i class="fa fa-trash"></i></a></button>
                        <input class='todolist-check' 
                                        type="checkbox" 
                                        id='${task.pk}' 
                                        value= '${task.pk}'
                                        name="finishbtn"
                                        ${task.fields.is_finished ?  'checked':''} 
                                        onchange="mark_as_finished(${task.pk})"
                                        />             
                    </div>`             

                }
                $('#card-container').html(text);

            } ,
            error: function(data){
                console.log('Error Detected');
            }
        })}

    function submitForm(){
            $.ajax({
                type: "POST",
                url: "{% url 'todolist:create_task_ajax' %}",
                data: {
                    title: $("#inputTitle").val(),
                    description: $("#inputDescription").val(),
                    csrfmiddlewaretoken: "{{ csrf_token }}",
                  },
                dataType: "json",
                success: function(){
                    $("#modalForm").modal('hide')
                    makeCards()
                },
                error: function(error){
                    alert("error")
                }
            })
            return false;
        
    }

    function delete_todolist(id){
        $.ajax({
          type :"DELETE",
          csrfmiddlewaretoken: "{{ csrf_token }}",
          url :`/todolist/delete/${id}`,
          success: function () {
            console.log("GREATSUCCESS")
            $(`#${id}`).remove()
            makeCards()
          },
          error: function(){
            console.log("GREATFAILURE")
          }
        })
    }

    
    function mark_as_finished(id){
        $.ajax({
        type :"UPDATE",
        csrfmiddlewaretoken: "{{ csrf_token }}",
        url :`/todolist/refresh/${id}`,
        success: function () {
          makeCards();  
        },
      })
      }
    
</script>

{% endblock content %}